version: "3.8"

networks:
  services_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.2.0/16

services:
  lockserver:
    container_name: t1distribuida
    ports:
    - 3000:5000
    networks:
      services_network:
        ipv4_address: 172.18.2.1
    build: .
    command: python lockserver.py 172.18.2.1 5000